# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
title: Awesome Badger
email: hello@red-badger.com
description: Assorted thinking (mostly) about technology written by the Badgers.
baseurl: ""
url: "https://awesome.red-badger.com/"
rburl: "https://red-badger.com/"
permalink: /:categories/:slug
twitter_username: RedBadgerTeam
github_username:  redbadger
linkedin_username: red-badger
author: Red Badger
show_excerpts: true
rss: RSS Feed

# Custom fields
copyright: "Red Badger Consulting Ltd"
logo: /assets/logo-awesome.png

plugins:
  - jekyll-redirect-from
  - jekyll-feed
